services:
    db:
        image: postgres
        restart: no
        shm_size: 128mb
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: soundboardTest
            POSTGRES_PASSWORD: password
            POSTGRES_DB: soundboard
        hostname: postgres-soundboard
        networks:
            postgres-network:
                aliases:
                    - postgres-soundboard
networks:
    postgres-network:
        external: true
