services:
    db:
        image: postgres
        restart: no
        shm_size: 128mb
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: soundboardTest
            POSTGRES_PASSWORD: password
            POSTGRES_DB: soundboard

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
